# Use a Node.js image for development
FROM node:18

# Set working directory
WORKDIR /backend

# Copy package.json and install dependencies
COPY ./backend/chat/package.json package.json
COPY ./backend/chat/package-lock.json ./package-lock.json

COPY ./backend/chat/install-bcrypt.sh /backend/install-bcrypt.sh

# Copy backend source code
COPY ./backend/chat .

# install new dependencies if any
RUN npm install

# uninstall the current bcrypt modules
RUN npm uninstall bcrypt

# install the bcrypt modules for the machine
RUN npm install bcrypt

# Install nodemon for hot-reloading
RUN npm install -g nodemon

# Expose the backend server's port
EXPOSE 8000

# Start the Express app with nodemon
CMD ["npm", "run", "start"]